---
title: "Oct-7-24"
format: html
editor: visual
---

Set up
```{r}
#clear the environment
rm(list = ls())
#Load in packages
library(tidyverse)
library(here)
```

Read in the data set
```{r}
tomatoes <- read.csv(here("Data", "tomato_data.csv"))
```

Assign data types
```{r}
tomatoes$Plant_number <- as.factor(tomatoes$Plant_number)
tomatoes$Treatment <- as.factor(tomatoes$Treatment)
```

Now fix factor levels
```{r}
fix <- which(tomatoes$Treatment == "control")
tomatoes$Treatment[fix] <- "Control"
fix2 <- which(tomatoes$Treatment == "fertilizer")
tomatoes$Treatment[fix2] <- "Fertilizer"

tomatoes$Treatment <- factor(tomatoes$Treatment)
levels(tomatoes$Treatment)
```

Now look at summary function
```{r}
test <- c(2, 4, 6, 8, 10, 12, 14, 16, 18, 20)
summary(test)

grades <- c(90, 94, 96, 90, 84, 86)
summary(grades)
```

We also have the quantile function (different way)
```{r}
quantile(grades, probs = c(0, 0.25, 0.5, 0.75, 1))
```

Using the dplyr package
```{r}
#Accessing the number of flowers column 
select(tomatoes, Num_flowers)
#Access the 3rd through 8th rows of data 
slice(tomatoes, 3:8)
#Access only rows from Control condition
filter(tomatoes, Treatment == "Control")
#Access data for plants that had at least 27 flowers
filter(tomatoes, Num_flowers > 27)
```