---
title: "Oct-9-2024"
format: html
editor: visual
---

Set up
```{r}
#Clear the environment
rm(list = ls())
#Load in packages
library(tidyverse)
library(here)
```

Load in the tomato data set
```{r}
tomato <- read.csv(here("Data","tomato_data.csv"))
```

Return the 3rd, 7th, and 9th rows of the data set
```{r}
#Here is one way
slice(tomato, c(3,7,9))
#Here is another 
tomato %>% slice(c(3,7,9))
#And another
tomato |> slice(c(3,7,9)) |> View()

```

Find all plants from fertilizer treatment with avg_tomato_weight_g greater 
than or equal to 145 g
```{r}
filter(tomato, Treatment == "Fertilizer" & Avg_tomato_weight_g >= 145)
```

Save your changes (to a new file in an output folder)

Make the output folder
```{r}
dir.create(here("Outputs"))
```

Now save the file
```{r}
write.csv(tomato, here("Outputs", "tomatoes_fixed.csv"), row.names = FALSE)
#row.names = F prevents R from adding a column of row numbers to the output file 
```

```{r}
toms2 <- read.csv(here("Outputs", "tomatoes_fixed.csv"))
```
